# Generated by Django 5.1 on 2024-09-03 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="app",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_app_id",
                to="school.appsetting",
            ),
        ),
    ]
