# Generated by Django 5.1 on 2024-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresse",
            },
        ),
    ]
