# Generated by Django 5.1 on 2024-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteLogo",
            new_name="SiteLogoModel",
        ),
    ]
