# Generated by Django 5.1 on 2024-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudo", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=15)),
                ("slug", models.SlugField(blank=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
